// Synthetic workshop data only; never connects to Firebase.
const fs=require('fs'),Module=require('module'),path=require('path'),assert=require('node:assert/strict');
const file=path.join(__dirname,'workflow.cjs');let source=fs.readFileSync(file,'utf8');source=source.slice(0,source.lastIndexOf('main().catch'))+';module.exports=fixture;';const mod=new Module(file);mod._compile(source,file);
const fixture=mod.exports,copy=x=>JSON.parse(JSON.stringify(x));let count=0;
function test(name,fn){fn();console.log('OK '+name);count++;}
const legacy={mesKey:'2026-09',titulo:'Septiembre 2026',zonas:{p1iz_Arriba:{telas:[{nombre:'Lisboa',metros:'1 palet y medio'},{nombre:'Bamboo',metros:'12,5'}]},carros_Viscofoam:{telas:[{nombre:'bamboo',metros:'2.5'}]}}};
const f=fixture(),c=f.ctx;c.aplicarDatos({inventarios:[legacy]});c.almAbrir(legacy);
test('decimal comma counted; free text excluded',()=>{const t=c.almTotales(legacy);assert.equal(t.metros,15);assert.equal(t.anotaciones,1);assert.equal(t.telas.length,2);});
test('legacy notes survive normalization without touching saved history',()=>{const n=c.almNormalizar(legacy);assert.equal(n.zonas.p1iz_Arriba.telas[0].notas,'1 palet y medio');assert.equal(n.zonas.p1iz_Arriba.telas[0].metros,'');assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.telas[0].metros,'1 palet y medio');});
test('autosave on typing persists immediately',()=>{c.almUpdateTela('p1iz_Arriba',1,'metros','25,75');assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.telas[1].metros,'25,75');});
test('partial decimal input stays editable rather than becoming a note',()=>{c.almUpdateTela('p1iz_Arriba',1,'metros','25,');c.almUpdateTela('p1iz_Arriba',1,'metros','25,5');const t=c.loadInventarios()[0].zonas.p1iz_Arriba.telas[1];assert.equal(t.metros,'25,5');assert.equal(t.notas,'');});
test('reopening restores autosaved draft',()=>{const fresh=fixture();fresh.ctx.aplicarDatos({inventarios:c.loadInventarios()});fresh.ctx.almAbrir(fresh.ctx.loadInventarios()[0]);assert.equal(fresh.run('almInventarioActual.zonas.p1iz_Arriba.telas[1].metros'),'25,5');});
test('pieces separate from meters',()=>{c.almUpdateTela('p1iz_Arriba',1,'piezas','3');const totals=c.almTotales(c.loadInventarios()[0]);assert.equal(totals.piezas,3);assert.equal(totals.metros,28);});
test('empty location can be explicitly reviewed',()=>{c.almRevisarZona('p2de_Abajo',true);assert.equal(c.loadInventarios()[0].zonas.p2de_Abajo.revisada,true);});
test('invalid values block review without losing the draft',()=>{c.almUpdateTela('p1iz_Arriba',1,'piezas','3,5');c.almRevisarZona('p1iz_Arriba',true);assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.revisada,false);assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.telas[1].piezas,'3,5');c.almUpdateTela('p1iz_Arriba',1,'piezas','3');});
test('edits reset reviewed status',()=>{c.almRevisarZona('p1iz_Arriba',true);assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.revisada,true);c.almUpdateTela('p1iz_Arriba',1,'metros','26');assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.revisada,false);});
test('finalize requires review of all locations',()=>{c.guardarInventario();assert.equal(c.loadInventarios()[0].borrador,true);c.almClaves().forEach(k=>c.almRevisarZona(k,true));c.guardarInventario();assert.equal(c.loadInventarios()[0].borrador,false);});
test('delete and undo restore the entire row',()=>{const before=copy(c.loadInventarios()[0].zonas.p1iz_Arriba.telas[1]);c.almDelTela('p1iz_Arriba',before.id);assert.equal(c.loadInventarios()[0].zonas.p1iz_Arriba.telas.length,1);f.els.get('undo-panel').children[1].click();assert.deepEqual(copy(c.loadInventarios()[0].zonas.p1iz_Arriba.telas[1]),before);});
test('next month retains reference only, resets counts and reviews',()=>{const next=c.almPreparar(c.loadInventarios()[0],'2026-10');const t=next.zonas.p1iz_Arriba.telas.find(x=>x.nombre==='Bamboo');assert.equal(t.metros,'');assert.equal(t.piezas,'');assert.equal(t.anterior.metros,'26');assert.equal(t.anterior.piezas,'3');assert.equal(c.almTotales(next).metros,0);assert.equal(c.almProgreso(next).revisadas,0);});
test('new month cannot overwrite an existing inventory',()=>{const before=copy(c.loadInventarios());c.prompt=()=> '2026-09';c.nuevoInventario();assert.deepEqual(copy(c.loadInventarios()),before);});
test('share explicitly chooses editor or historical month',()=>{c.almAbrir(c.almPreparar(c.loadInventarios()[0],'2026-10'));c.almUpdateTela('p1iz_Arriba',1,'metros','40');f.run("almDetalleKey='2026-09'");let url;c.open=u=>url=decodeURIComponent(u);c.compartirInventarioWhatsApp('actual');assert.match(url,/Octubre 2026/);assert.match(url,/40 m/);c.compartirInventarioWhatsApp('detalle');assert.match(url,/Septiembre 2026/);assert.match(url,/26 m/);});
test('JSON roundtrip includes pieces, notes, reference and review',()=>{const b={version:3,...c.datosTaller()},restored=c.validarCopia(b);assert.deepEqual(copy(restored.inventarios),copy(c.loadInventarios()));});
test('independent local and remote edits both survive',()=>{const rows=c.loadInventarios(),old=rows.find(i=>i.mesKey==='2026-09');c.almAbrir(old);const remote=copy(rows);remote.find(i=>i.mesKey==='2026-09').zonas.carros_Viscofoam.telas[0].metros='50';c.aplicarDatos({inventarios:remote});c.almUpdateTela('p1iz_Arriba',1,'metros','27');const saved=c.loadInventarios().find(i=>i.mesKey==='2026-09');assert.equal(saved.zonas.carros_Viscofoam.telas[0].metros,'50');assert.equal(saved.zonas.p1iz_Arriba.telas[1].metros,'27');});
test('conflict does not silently overwrite another count',()=>{const rows=copy(c.loadInventarios());rows.find(i=>i.mesKey==='2026-09').zonas.p1iz_Arriba.telas[1].metros='90';c.aplicarDatos({inventarios:rows});c.almUpdateTela('p1iz_Arriba',1,'metros','30');assert.equal(c.loadInventarios().find(i=>i.mesKey==='2026-09').zonas.p1iz_Arriba.telas[1].metros,'90');assert.match(f.els.get('alm-estado').textContent,/Sin guardar/);assert(f.store.has('daurela_recuperacion_v3'));});
test('failed storage write shows unsaved and preserves previous saved inventory',()=>{const g=fixture(),d=g.ctx;d.aplicarDatos({inventarios:[legacy]});d.almAbrir(legacy);const saved=copy(d.loadInventarios()),set=d.localStorage.setItem;d.localStorage.setItem=(key,v)=>{if(key==='almacen_v1')throw Error('Sin espacio');set(key,v);};d.almUpdateTela('p1iz_Arriba',1,'metros','60');assert.deepEqual(copy(d.loadInventarios()),saved);assert.match(g.els.get('alm-estado').textContent,/Sin guardar/);});
test('render works with compact zones and datalist',()=>{const g=fixture();g.ctx.aplicarDatos({inventarios:[legacy]});g.ctx.almAbrir(legacy);g.ctx.renderFormularioAlmacen();assert.equal(g.els.get('alm-formulario').children.length,3);assert.equal(g.els.get('alm-formulario').children[0].tagName,'details');assert(g.els.get('alm-nombres').children.length>=2);});

test('clients and formats survive autosave, copy, summary and next month',()=>{
  const g=fixture(),d=g.ctx;d.aplicarDatos({inventarios:[legacy]});d.almAbrir(legacy);
  d.almUpdateTela('p1iz_Arriba',1,'cliente','Paco');d.almUpdateTela('p1iz_Arriba',1,'formato','tacos');d.almUpdateTela('p1iz_Arriba',1,'piezas','4');
  d.almUpdateTela('carros_Viscofoam',0,'cliente','Otro cliente');d.almUpdateTela('carros_Viscofoam',0,'piezas','2');
  const inv=d.loadInventarios()[0],tot=d.almTotales(inv);assert.equal(tot.tacos,4);assert.equal(tot.piezas,2);assert.equal(tot.telas.filter(x=>x.nombre.toLowerCase()==='bamboo').length,2);
  assert.match(d.almTextoCompartir(inv),/Bamboo · Paco: 12,5 m · 4 tacos/);assert.match(d.almTextoCompartir(inv),/bamboo · Otro cliente: 2,5 m · 2 piezas/);
  const next=d.almPreparar(inv,'2026-10').zonas.p1iz_Arriba.telas[1];assert.equal(next.cliente,'Paco');assert.equal(next.formato,'tacos');assert.equal(next.piezas,'');assert.equal(next.anterior.formato,'tacos');assert.match(d.almCantidad(next.anterior),/4 tacos/);
  const restored=d.validarCopia({version:3,...d.datosTaller()});assert.equal(restored.inventarios[0].zonas.p1iz_Arriba.telas[1].formato,'tacos');
  d.almUpdateTela('p1iz_Arriba',1,'formato','piezas');assert.equal(d.almTotales(d.loadInventarios()[0]).piezas,6);assert.equal(d.almTotales(d.loadInventarios()[0]).tacos,0);
  const bad={version:3,...copy(d.datosTaller())};bad.inventarios[0].zonas.p1iz_Arriba.telas[1].formato='palets';assert.throws(()=>d.validarCopia(bad));
});
console.log(count+' warehouse checks passed.');
