const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm');
const {stock,bajos,nuevosAvisos,validarSuscripcion}=require('../functions/materiales').testHelpers;
const material=n=>({id:'bolsas',nombre:'Bolsas Lisboa',minimo:500,movimientos:[{cantidad:n}]});
const data=n=>({materiales:[material(n)]});
assert.equal(stock(material(1880)),1880);
assert.equal(bajos(data(501)).length,0);
assert.equal(bajos(data(500)).length,1);
assert.equal(nuevosAvisos(data(1880),data(500)).length,1);
assert.equal(nuevosAvisos(data(500),data(300)).length,0);
assert.equal(nuevosAvisos(data(300),data(0)).length,1);
assert.equal(nuevosAvisos(data(0),data(0)).length,0);
assert.equal(nuevosAvisos(data(0),data(1000)).length,0);
assert.equal(nuevosAvisos(data(1000),data(400)).length,1);
assert.equal(nuevosAvisos({},data(100)).length,1);
const sub={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:'A'.repeat(87),auth:'B'.repeat(22)}};
assert.deepEqual(validarSuscripcion(sub),sub);
for(const endpoint of ['http://localhost','https://127.0.0.1','https://fcm.googleapis.com.evil.com/x','https://fcm.googleapis.com:8443/x','https://user@fcm.googleapis.com/x'])assert.throws(()=>validarSuscripcion({...sub,endpoint}));
assert.throws(()=>validarSuscripcion({...sub,keys:{p256dh:'bad',auth:'bad'}}));
assert.throws(()=>validarSuscripcion(null));
const events={},notifications=[];
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../sw.js'),'utf8'),{self:{addEventListener:(type,fn)=>events[type]=fn,registration:{showNotification:(title,options)=>{notifications.push({title,options});return Promise.resolve();}}}});
events.push({data:{json:()=>({title:'Prueba',body:'Quedan 500',tag:'materiales-bajos'})},waitUntil(){}});
assert.equal(notifications[0].options.body,'Quedan 500');
assert.equal(notifications[0].options.data.url,'/Daurela/#materiales');
assert.equal(typeof events.notificationclick,'function');
console.log('OK push: threshold, zero, no repeat, replenish, authentication endpoint validation and service-worker notification.');
